AWSTemplateFormatVersion: "2010-09-09"
Resources:
  MyFirstInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: "ami-0ad21ae1d0696ad58"
      InstanceType: "t2.micro"
      Tags:
        - Key: "Name"
          Value: !Join [ ":", [ MyFirstInstance, !Ref AWS::Region ] ]
